## This file configures generic OIDC auth that is used in conjunction with GenericOidcConfig.kt,
#  GenericOidcUserAuthenticationResolver.kt etc. It can be loaded by including the `generic-oidc`
# value in MICRONAUT_ENVIRONMENTS.
micronaut:
  security:
    enabled: ${API_AUTHORIZATION_ENABLED:false}
    token:
      jwt:
        enabled: ${API_AUTHORIZATION_ENABLED:false}
        signatures:
          jwks:
            oidc:
              url: ${AB_AIRBYTE_AUTH_JWKS_ENDPOINT:}
