apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-airbyte-secrets
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "airbyte.airbyte.secrets" . | nindent 2 }}
  {{- include "airbyte.auth.bootstrap.secrets" . | nindent 2 }}
  {{- include "airbyte.auth.security.secrets" . | nindent 2 }}
  {{- include "airbyte.connector.secrets" . | nindent 2 }}
  {{- include "airbyte.cron.secrets" . | nindent 2 }}
  {{- include "airbyte.customerio.secrets" . | nindent 2 }}
  {{- include "airbyte.database.secrets" . | nindent 2 }}
  {{- include "airbyte.database.migrations.secrets" . | nindent 2 }}
  {{- include "airbyte.datadog.secrets" . | nindent 2 }}
  {{- include "airbyte.email.secrets" . | nindent 2 }}
  {{- include "airbyte.featureFlags.secrets" . | nindent 2 }}
  {{- include "airbyte.featureFlags.launchdarkly.secrets" . | nindent 2 }}
  {{- include "airbyte.logging.secrets" . | nindent 2 }}
  {{- include "airbyte.metrics.secrets" . | nindent 2 }}
  {{- include "airbyte.secretsManager.secrets" . | nindent 2 }}
  {{- include "airbyte.storage.secrets" . | nindent 2 }}
  {{- include "airbyte.temporal.secrets" . | nindent 2 }}
  {{- include "airbyte.temporal.cli.secrets" . | nindent 2 }}
  {{- include "airbyte.temporal.cloud.secrets" . | nindent 2 }}
  {{- include "airbyte.tracking.secrets" . | nindent 2 }}
  {{- include "airbyte.workloadApiServer.secrets" . | nindent 2 }}
  {{- include "airbyte.workloads.secrets" . | nindent 2 }}

  {{- if or (eq .Values.global.edition "enterprise") (eq .Values.global.edition "pro") -}}
  {{- include "airbyte.auth.identityProvider.secrets" . | nindent 2 }}
  {{- include "airbyte.auth.instanceAdmin.enterprise.secrets" . | nindent 2 }}
  {{- include "airbyte.enterprise.secrets" . | nindent 2 }}
  {{- include "airbyte.keycloak.secrets" . | nindent 2 }}
  {{- end }}
