# .github/workflows/auto-close-prs.yml
name: Auto-Close Incoming PRs

on:
  pull_request:
    types: [opened]

jobs:
  auto-close:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment and close PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;

            const message = `Hi, so that we can focus on supporting our connector contributors, we not longer accept PRs in this repo. Please feel free to post issues in https://github.com/airbytehq/airbyte. We encourage contributions in all of our other public repos including https://github.com/airbytehq/airbyte.`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: message
            });

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              state: "closed"
            });
