# .github/workflows/auto-close-prs.yml
name: Auto-Close Incoming PRs (including from forks)

on:
  pull_request:
    types: [opened]

jobs:
  auto-close:
    runs-on: ubuntu-latest
    steps:
      - name: Comment and close PR
        uses: actions/github-script@v7
        with:
          token: ${{ secrets.BOT_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;

            const message = `So we can focus on supporting our connector contributors, we do accept PRs in this repo. Please feel free to post an issue in https://github.com/airbytehq/airbyte. We encourage contributions in all of our other public repos including https://github.com/airbytehq/airbyte.`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: message
            });

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              state: "closed"
            });
